### ISSUE TITLE
ImportError: cannot import name 'dump_rows'

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#107]
python experiments/ner/prepro.py
Traceback (most recent call last):
  File "experiments/ner/prepro.py", line 7, in <module>
    from experiments.ner.ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos, dump_rows
ImportError: cannot import name 'dump_rows' from 'experiments.ner.ner_utils' (/home/ant/multitask/mt-dnn/experiments/ner/ner_utils.py)

I tried to fix it with the below changes
--from experiments.ner.ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos, dump_rows
++from experiments.ner.ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos

BUT, I think that it is just needed a specific for ner implementation in experiments/ner/ner_utils.py

**Comment by namisan** [comment]
done

**Comment by antgr** [comment]
I made the following change
-from experiments.ner.ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos
+from ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos
in order to solve the following issue:
```python experiments/ner/prepro.py
Traceback (most recent call last):
  File "experiments/ner/prepro.py", line 7, in <module>
    from experiments.ner.ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos
ImportError: No module named ner.ner_utils```

To solve the issues, the diff is the following
-from experiments.ner.ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos
+from ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos
 from experiments.common_utils import dump_rows
 logger = create_logger(__name__, to_disk=True, log_file='bert_ner_data_proc_512_cased.log')
 
@@ -54,27 +54,27 @@ def main(args):
     dev_fout = os.path.join(bert_root, 'ner_dev.tsv')
     test_fout = os.path.join(bert_root, 'ner_test.tsv')
 
-    dump_rows(train_data, train_fout)
-    dump_rows(dev_data, dev_fout)
-    dump_rows(test_data, test_fout)
+    dump_rows(train_data, train_fout,DataFormat.Seqence)
+    dump_rows(dev_data, dev_fout,DataFormat.Seqence)
+    dump_rows(test_data, test_fout, DataFormat.Seqence)
     logger.info('done with NER')
 
     train_fout = os.path.join(bert_root, 'pos_train.tsv')
     dev_fout = os.path.join(bert_root, 'pos_dev.tsv')
     test_fout = os.path.join(bert_root, 'pos_test.tsv')
-    dump_rows(pos_train_data, train_fout)
-    dump_rows(pos_dev_data, dev_fout)
-    dump_rows(pos_test_data, test_fout)
+    dump_rows(pos_train_data, train_fout, DataFormat.Seqence)
+    dump_rows(pos_dev_data, dev_fout, DataFormat.Seqence)
+    dump_rows(pos_test_data, test_fout, DataFormat.Seqence)
     logger.info('done with POS')
 
     train_fout = os.path.join(bert_root, 'chunk_train.tsv')
     dev_fout = os.path.join(bert_root, 'chunk_dev.tsv')
     test_fout = os.path.join(bert_root, 'chunk_test.tsv')
-    dump_rows(chunk_train_data, train_fout)
-    dump_rows(chunk_dev_data, dev_fout)
-    dump_rows(chunk_test_data, test_fout)
+    dump_rows(chunk_train_data, train_fout, DataFormat.Seqence)
+    dump_rows(chunk_dev_data, dev_fout, DataFormat.Seqence)
+    dump_rows(chunk_test_data, test_fout, DataFormat.Seqence)
     logger.info('done with chunk')
