### ISSUE TITLE
Problem with Apex

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#111]
python3 train.py --data-dir ner/ --init_checkpoint mt_dnn_models/bert_model_base_uncased.pt -train_dataset ner --test_dataset ner --task_def experiments/ner/ner_task_def.yml 
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from pytorch_pretrained_bert.modeling import BertConfig
  File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/__init__.py", line 7, in <module>
    from .modeling import (BertConfig, BertModel, BertForPreTraining,
  File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 218, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm as BertLayerNorm
  File "/home/user/.local/lib/python3.7/site-packages/apex/__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "/home/user/.local/lib/python3.7/site-packages/apex/interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "/home/user/.local/lib/python3.7/site-packages/apex/interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "/usr/lib64/python3.7/site-packages/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

I have the following version of APEX
pip3 show apex
Name: apex
Version: **0.9.10.dev0**

**Comment by namisan** [comment]
could you follow instruction about env? it is python3.6.
