### ISSUE TITLE
Early detection of not enough hardware requirments

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#114]
I wonder if the scripts could be enhanced in order to detect hardware (gpu) and print warning that there is not enough hardware for the experiment (or ideally to suggest settings e.g batch size etc).

For example the following run lasted from 08:27:29 to 08:53:12, and then crashed.

Could you help me understand why the specific experiment needs so much gpu memory?
I used 'init_checkpoint': 'mt_dnn_models/mt_dnn_base_uncased.pt'
and 'init_checkpoint': 'mt_dnn_models/bert_model_base_uncased.pt', with the same result bellow.

Thanks a lot.

```
10/22/2019 08:27:29 Total number of params: 130194453
10/22/2019 08:27:29 At epoch 0
10/22/2019 08:27:29 Task [ 7] updates[     1] train loss[14.33726] remaining[6:04:43]
10/22/2019 08:28:41 Task [ 0] updates[   500] train loss[1.01641] remaining[4:42:22]
10/22/2019 08:29:54 Task [ 0] updates[  1000] train loss[0.96663] remaining[4:44:18]
10/22/2019 08:31:08 Task [ 2] updates[  1500] train loss[0.98181] remaining[4:45:35]
10/22/2019 08:32:22 Task [ 0] updates[  2000] train loss[0.96799] remaining[4:44:42]
10/22/2019 08:33:36 Task [ 2] updates[  2500] train loss[0.95632] remaining[4:44:22]
10/22/2019 08:34:50 Task [ 0] updates[  3000] train loss[0.95055] remaining[4:43:34]
10/22/2019 08:36:04 Task [ 0] updates[  3500] train loss[0.94487] remaining[4:42:13]
10/22/2019 08:37:17 Task [ 2] updates[  4000] train loss[0.93659] remaining[4:40:50]
10/22/2019 08:38:31 Task [ 0] updates[  4500] train loss[0.93057] remaining[4:39:57]
10/22/2019 08:39:44 Task [ 2] updates[  5000] train loss[0.93538] remaining[4:38:22]
10/22/2019 08:40:57 Task [ 5] updates[  5500] train loss[0.93393] remaining[4:36:56]
10/22/2019 08:42:10 Task [ 2] updates[  6000] train loss[0.93207] remaining[4:35:50]
10/22/2019 08:43:24 Task [ 0] updates[  6500] train loss[0.92663] remaining[4:34:44]
10/22/2019 08:44:37 Task [ 2] updates[  7000] train loss[0.92031] remaining[4:33:15]
10/22/2019 08:45:50 Task [ 0] updates[  7500] train loss[0.91180] remaining[4:31:55]
10/22/2019 08:47:04 Task [ 3] updates[  8000] train loss[0.90517] remaining[4:30:53]
10/22/2019 08:48:18 Task [ 0] updates[  8500] train loss[0.89916] remaining[4:29:47]
10/22/2019 08:49:32 Task [ 2] updates[  9000] train loss[0.89482] remaining[4:28:40]
10/22/2019 08:50:45 Task [ 3] updates[  9500] train loss[0.88491] remaining[4:27:22]
10/22/2019 08:51:59 Task [ 3] updates[ 10000] train loss[0.87999] remaining[4:26:06]
10/22/2019 08:53:12 Task [ 0] updates[ 10500] train loss[0.87275] remaining[4:24:57]
/usr/lib64/python3.7/site-packages/sklearn/externals/six.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/lib64/python3.7/site-packages/sklearn/utils/__init__.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sequence
Traceback (most recent call last):
  File "train.py", line 434, in <module>
    main()
  File "train.py", line 369, in main
    model.update(batch_meta, batch_data)
  File "/home/user/mt-dnn/mt_dnn/model.py", line 195, in update
    logits = self.mnetwork(*inputs)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/mt-dnn/mt_dnn/matcher.py", line 97, in forward
    all_encoder_layers, pooled_output = self.bert(input_ids, token_type_ids, attention_mask)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 714, in forward
    output_all_encoded_layers=output_all_encoded_layers)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 396, in forward
    hidden_states = layer_module(hidden_states, attention_mask)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 382, in forward
    intermediate_output = self.intermediate(attention_output)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 355, in forward
    hidden_states = self.intermediate_act_fn(hidden_states)
  File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 119, in gelu
    return x * 0.5 * (1.0 + torch.erf(x / math.sqrt(2.0)))
RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 10.92 GiB total capacity; 9.53 GiB already allocated; 39.50 MiB free; 771.55 MiB cached)
^C
[1]+  Exit 1                  nohup sh scripts/run_mt_dnn.sh 8 0 > run_mt_dnn.logs
```

**Comment by namisan** [comment]
check your max seq length.
