### ISSUE TITLE
prepro_std.py does not support sequence tasks

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#121]
running prepro_std.py  for sequence task, gives an error:
(also the spelling is incorrect: Seqence --> Sequence)
```
python prepro_std.py --model bert-base-uncased --root_dir ner --task_def experiments/ner/ner_task_def.yml 
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
11/04/2019 09:31:52 Task ner
data_format:  DataFormat.Seqence
Traceback (most recent call last):
  File "prepro_std.py", line 551, in <module>
    main(args)
  File "prepro_std.py", line 536, in main
    label_mapper)
  File "prepro_std.py", line 433, in load_data
    raise ValueError(data_format)
ValueError: DataFormat.Seqence
```

The missing implementation I think is in load data, in final else (implementation for data_format `Seqence` is missing):
```
    if task_type == TaskType.Ranking:
        assert data_format == DataFormat.PremiseAndMultiHypothesis

    rows = []
    for line in open(file_path, encoding="utf-8"):
        fields = line.strip("\n").split("\t")
        if data_format == DataFormat.PremiseOnly:
            assert len(fields) == 3
            row = {"uid": fields[0], "label": fields[1], "premise": fields[2]}
        elif data_format == DataFormat.PremiseAndOneHypothesis:
            assert len(fields) == 4
            row = {
                "uid": fields[0],
                "label": fields[1],
                "premise": fields[2],
                "hypothesis": fields[3]}
        elif data_format == DataFormat.PremiseAndMultiHypothesis:
            assert len(fields) > 5
            row = {"uid": fields[0], "ruid": fields[1].split(","), "label": fields[2], "premise": fields[3],
                   "hypothesis": fields[4:]}
        else:
            print ("data_format: ", data_format)
            raise ValueError(data_format) <---- here is the exception
```

**Comment by antgr** [comment]
@namisan  any estimation for that? Do you want my help for the implementation? Guide me and I will create a PR.

**Comment by namisan** [comment]
I'll check it in soon. 
Xiaodong

**Comment by antgr** [comment]
@namisan namisan
Any news on that? I added handling for seq, with the same logic as for premise only case. I just parsed the strings as lists for labels and premise, using ast library.
So, json files created, but labels, remained as strings, for example 'O'. I changed them mapping each label to a number I chose. e.g 20,21,22 etc
Then I ran the model for ner, but I had an exception from cuda. This error I believe has to do with the selected numbers for the labels, or maybe something else. Any idea if my approach is correct, and if not how I could workaround this missing implementation?

**Comment by antgr** [comment]
changes:
```
+    import ast
     for line in open(file_path, encoding="utf-8"):
         fields = line.strip("\n").split("\t")
-        if data_format == DataFormat.PremiseOnly:
+        if data_format == DataFormat.PremiseOnly or data_format == DataFormat.Seqence:
             assert len(fields) == 3
-            row = {"uid": fields[0], "label": fields[1], "premise": fields[2]}
+            lab = ast.literal_eval(fields[1])
+            prem = ast.literal_eval(fields[2])
+            assert (len(lab) == len(prem))
+            row = {"uid": fields[0], "label": lab, "premise": prem }
```

**Comment by antgr** [comment]
I run :
```python prepro_std.py --model bert-base-uncased --root_dir ner --task_def experiments/ner/ner_task_def.yml ```

and here is some lines of ner_train.json
head  ner/ner_train.tsv
```
0	['I-ORG', 'O', 'I-MISC', 'O', 'O', 'O', 'I-MISC', 'O', 'O']	['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.']
1	['I-PER', 'I-PER']	['Peter', 'Blackburn']
2	['I-LOC', 'O']	['BRUSSELS', '1996-08-22']
3	['O', 'I-ORG', 'I-ORG', 'O', 'O', 'O', 'O', 'O', 'O', 'I-MISC', 'O', 'O', 'O', 'O', 'O', 'I-MISC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']	['The', 'European', 'Commission', 'said', 'on', 'Thursday', 'it', 'disagreed', 'with', 'German', 'advice', 'to', 'consumers', 'to', 'shun', 'British', 'lamb', 'until', 'scientists', 'determine', 'whether', 'mad', 'cow', 'disease', 'can', 'be', 'transmitted', 'to', 'sheep', '.']
```
Something wrong is with this file:
I run
```python train.py --data_dir ner/bert_uncased/ --init_checkpoint mt_dnn_models/bert_model_base_uncased.pt --train_dataset ner --test_dataset ner --task_def experiments/ner/ner_task_def.yml ```
and here is the error:
```
12/12/2019 11:17:26 Total number of params: 109491468
12/12/2019 11:17:26 At epoch 0
Traceback (most recent call last):
  File "train.py", line 434, in <module>
    main()
  File "train.py", line 368, in main
    batch_meta, batch_data = next(all_iters[task_id])
  File "/home/polykratis/mt-dnn/mt_dnn/batcher.py", line 149, in __iter__
    tlab[i, : ll] = torch.LongTensor(label)
TypeError: an integer is required (got type str)
```
