### ISSUE TITLE
exception for TaskType TaskLM

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#141]
After adding dev.json and test.json:
01/26/2020 12:41:24 Task [ 0] updates[     1] train loss[10.20193] remaining[0:00:05]
predicting 0
Traceback (most recent call last):
  File "train.py", line 402, in <module>
    main()
  File "train.py", line 361, in main
    task_type=task_defs.task_type_map[prefix])
  File "/home/<user>/mt-dnn/mt_dnn/inference.py", line 18, in eval_model
    score, pred, gold = model.predict(batch_info, batch_data)
  File "/home/<user>/mt-dnn/mt_dnn/model.py", line 248, in predict
    score = score.data.cpu()
AttributeError: 'tuple' object has no attribute 'data'

**Comment by namisan** [comment]
It only supports training not evaluation.
