### ISSUE TITLE
Error when using mt_dnn_base_uncased in extractor.py

### ISSUE THREAD

**Issue by jubs12** [namisan/mt-dnn#151]
When running with mt_dnn_base_uncased, 
`python extractor.py --do_lower_case --finput dataset.txt --foutput dataset.json --bert_model mt_dnn_models/mt_dnn_base_uncased.pt  --checkpoint mt_dnn_models/mt_dnn_base_uncased.pt`

it gets the following error:

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
Traceback (most recent call last):
  File "extractor.py", line 199, in <module>
    main()
  File "extractor.py", line 154, in main
    data, is_single_sentence = process_data(args)
  File "extractor.py", line 136, in process_data
    tokenizer = BertTokenizer.from_pretrained(args.bert_model, do_lower_case=args.do_lower_case)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/tokenization.py", line 153, in from_pretrained
    tokenizer = cls(resolved_vocab_file, *inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/tokenization.py", line 83, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/tokenization.py", line 56, in load_vocab
    token = reader.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by namisan** [comment]
Make sure the byte order mark of your text if it includes non-english characters.
