### ISSUE TITLE
F1 score fails for multiclass classification

### ISSUE THREAD

**Issue by mariamedp** [namisan/mt-dnn#154]
calc_metrics fails when trying to use F1 as a metric in multiclass classification:

```
Traceback (most recent call last):
  ...
  File "<path>\data_utils\metrics.py", line 18, in compute_f1
    return 100.0 * f1_score(labels, predicts)
  File "<path>\lib\site-packages\sklearn\metrics\_classification.py", line 1099, in f1_score    
    zero_division=zero_division)
  File "<path>\lib\site-packages\sklearn\metrics\_classification.py", line 1226, in fbeta_score 
    zero_division=zero_division)
  File "<path>\lib\site-packages\sklearn\metrics\_classification.py", line 1484, in precision_recall_fscore_support
    pos_label)
  File "<path>\lib\site-packages\sklearn\metrics\_classification.py", line 1316, in _check_set_wise_labels
    % (y_type, average_options))
ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].
```

The equivalent to what accuracy_score does in multiclass would be:
```
100.0 * f1_score(labels, predicts, average='macro')
```
but I'm not sure if that's the desired behaviour or it would be better to add extra metrics F1macro, F1micro, etc.

**Comment by namisan** [comment]
Thanks @mariamedp, I've added these metrics and will update it soon.
xiaodong

**Comment by mariamedp** [comment]
Thank you!
