### ISSUE TITLE
add more detail about how to train a roberta+alum?

### ISSUE THREAD

**Issue by RyanHuangNLP** [namisan/mt-dnn#172]
Through the paper I know that is first to pretrain a roberta(it is already done by fb), second to continue train with alum, but I wonder how to merge to code below the alum into fairseq to run the trainning code?

**Comment by namisan** [comment]
Will update the readme.

**Comment by RyanHuangNLP** [comment]
I know that how to merge the code into fairseq to train alum, following the paper's description: `we use RoBERTa’s default training parameters, except a smaller learning rate(4 × 10−5), and run for 100K training steps with a batch size of 256 on the union of Wikipedia, OPENWEBTEXT, and STORIES (total size 82GB`, is it same to the roberta base and roberta large?

**Comment by namisan** [comment]
Yes, it is.

**Comment by RyanHuangNLP** [comment]
Hello, I was wonder that what is the version of fairseq is using? I ran on fairseq 0.9.0, raise following error

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/alum/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/dockerdata/ramseyhuang/fairseq/fairseq_cli/train.py", line 370, in cli_main
    nprocs=args.distributed_world_size,
  File "/root/miniconda3/envs/alum/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/root/miniconda3/envs/alum/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/alum/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/dockerdata/ramseyhuang/fairseq/fairseq_cli/train.py", line 338, in distributed_main
    main(args, init_distributed=True)
  File "/dockerdata/ramseyhuang/fairseq/fairseq_cli/train.py", line 72, in main
    criterion = task.build_criterion(args)
  File "/dockerdata/ramseyhuang/fairseq/fairseq/tasks/fairseq_task.py", line 230, in build_criterion
    return criterions.build_criterion(args, self)
  File "/dockerdata/ramseyhuang/fairseq/fairseq/registry.py", line 41, in build_x
    return builder(args, *extra_args, **extra_kwargs)
  File "/dockerdata/ramseyhuang/fairseq/fairseq/criterions/fairseq_criterion.py", line 56, in build_criterion
    '{}.build_criterion'.format(cls.__name__)
NotImplementedError: Unable to infer Criterion arguments, please implement AdvMaskedLmLoss.build_criterion
```

**Comment by RyanHuangNLP** [comment]
thank you very much, I will take a try
