### ISSUE TITLE
Failed to run train.py

### ISSUE THREAD

**Issue by TamHHM** [namisan/mt-dnn#182]
I ran docker image:
```
python train.py --task_def tutorials/tutorial_task_def.yml --data_dir tutorials/bert_base_uncased/ --train_datasets snlisample --test_datasets snlisample 
```
and get the following error:
```
Traceback (most recent call last):
  File "train.py", line 382, in <module>
    main()
  File "train.py", line 313, in main
    model.update(batch_meta, batch_data)
  File "/home/tam/Klarrio/Twitter/mt-dnn/mt_dnn/model.py", line 199, in update
    logits = self.mnetwork(*inputs)
  File "/home/tam/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tam/Klarrio/Twitter/mt-dnn/mt_dnn/matcher.py", line 205, in forward
    sequence_output, pooled_output = self.encode(input_ids, token_type_ids, attention_mask)
ValueError: too many values to unpack (expected 2)
```

The same error would happen if I installed and run train.py on my machine.

**Comment by namisan** [comment]
fixed
