### ISSUE TITLE
Got problems when preproduce HNN result

### ISSUE THREAD

**Issue by Cy30mk3v** [namisan/mt-dnn#203]
While I run the script for preproduce HNN. I got:
`Traceback (most recent call last):
  File "/content/mt-dnn/hnn/script/../src/apps/run_hnn.py", line 588, in <module>
    main(args)
  File "/content/mt-dnn/hnn/script/../src/apps/run_hnn.py", line 476, in main
    train_model(args, device, n_gpu, model, train_data, eval_data, num_train_steps)
  File "/content/mt-dnn/hnn/script/../src/apps/run_hnn.py", line 133, in train_model
    prefix='{}-{}'.format(n_epoch, args.num_train_epochs))
  File "/content/mt-dnn/hnn/script/../src/apps/run_hnn.py", line 266, in run_eval
    sm_logits, lm_logits, en_logits, tmp_eval_loss = model(input_ids, tids, label_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/mt-dnn/hnn/src/apps/hnn_model.py", line 360, in forward
    sm_logits, sm_loss = self.sm_matcher(self.bert, sm_inputs, sm_labels)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/mt-dnn/hnn/src/apps/hnn_model.py", line 150, in forward
    encoder_layers = bert(token_ids, type_ids, mask_ids, output_all_encoded_layers=True, return_att=return_att)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/mt-dnn/hnn/src/apps/hnn_model.py", line 52, in forward
    embedding_output = self.embeddings(input_ids.to(torch.long), token_type_ids.to(torch.long), position_ids, input_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/mt-dnn/hnn/src/bert/modeling.py", line 171, in forward
    words_embeddings = self.word_embeddings(input_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1814, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select`
I ran on Google Colab with Nvidia V100, with previous tasks they all recognized the cuda device but not this one. Appreciate the help

**Comment by orkuntemiz** [comment]
Hello, How did you run the code in the colab, can you share me the implementation please. I did not get it run at all

**Comment by Cy30mk3v** [comment]
> Hello, How did you run the code in the colab, can you share me the implementation please. I did not get it run at all

I have a little bit of adjustment in dataset (fill with GLUE datasets). Try to make sure the file prepro.sh run correctly. Here's my colab notebook: https://colab.research.google.com/drive/13sTjuOy2pbfV_nwyGpHU-JPzX7MWT_O6?usp=sharing

**Comment by namisan** [comment]
thanks @Cy30mk3v
