### ISSUE TITLE
how to pretrain a bert_model_base_v2.pt ?

### ISSUE THREAD

**Issue by Gpwner** [namisan/mt-dnn#46]

**Comment by Gpwner** [comment]
is there any way to pretrain a pt model using custom data？

**Comment by Gpwner** [comment]
I am trying to convert a tensorflow pretrain model which is ckpt format to pt model using [the script](https://github.com/huggingface/pytorch-pretrained-BERT#Command-line-interface).

This script does complete the conversion ，but i can not use it to finetune.
And I got the following error:
```
06/13/2019 04:42:32 ####################
06/13/2019 04:42:32 {'log_file': 'checkpoints/mt-dnn-rte_adamax_answer_opt1_gc0_ggc1_2019-06-13T1642/log.log', 'init_checkpoint': '../mt_dnn_models/base_model.pt', 'data_dir': '../data/mt_dnn', 'data_sort_on': False, 'name': 'farmer', 'train_datasets': ['mnli', 'rte', 'qqp', 'qnli', 'mrpc', 'sst', 'cola', 'stsb'], 'test_datasets': ['mnli_matched', 'mnli_mismatched', 'rte'], 'pw_tasks': ['qnnli'], 'update_bert_opt': 0, 'multi_gpu_on': True, 'mem_cum_type': 'simple', 'answer_num_turn': 5, 'answer_mem_drop_p': 0.1, 'answer_att_hidden_size': 128, 'answer_att_type': 'bilinear', 'answer_rnn_type': 'gru', 'answer_sum_att_type': 'bilinear', 'answer_merge_opt': 1, 'answer_mem_type': 1, 'answer_dropout_p': 0.1, 'answer_weight_norm_on': False, 'dump_state_on': False, 'answer_opt': [1, 1, 1, 1, 1, 0, 0, 0], 'label_size': '3,2,2,2,2,2,2,1', 'mtl_opt': 0, 'ratio': 0, 'mix_opt': 0, 'max_seq_len': 128, 'init_ratio': 1, 'cuda': True, 'log_per_updates': 500, 'epochs': 5, 'batch_size': 32, 'batch_size_eval': 8, 'optimizer': 'adamax', 'grad_clipping': 0.0, 'global_grad_clipping': 1.0, 'weight_decay': 0, 'learning_rate': 5e-05, 'momentum': 0, 'warmup': 0.1, 'warmup_schedule': 'warmup_linear', 'vb_dropout': True, 'dropout_p': 0.1, 'dropout_w': 0.0, 'bert_dropout_p': 0.1, 'ema_opt': 0, 'ema_gamma': 0.995, 'have_lr_scheduler': True, 'multi_step_lr': '10,20,30', 'freeze_layers': -1, 'embedding_opt': 0, 'lr_gamma': 0.5, 'bert_l2norm': 0.0, 'scheduler_type': 'ms', 'output_dir': 'checkpoints/mt-dnn-rte_adamax_answer_opt1_gc0_ggc1_2019-06-13T1642', 'seed': 2018, 'task_config_path': 'configs/tasks_config.json', 'tasks_dropout_p': [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]}
06/13/2019 04:42:32 ####################
Traceback (most recent call last):
  File "../train.py", line 358, in <module>
    main()
  File "../train.py", line 255, in main
    config = state_dict['config']
KeyError: 'config'

```
Any help will be appreciate!

**Comment by namisan** [comment]
You just follow the instructions of training a large MT-DNN. By replacing the large BERT by a base BERT model. You are able to train one. 

Regarding converting issues, I have a tool, but it requires TF env which makes many potential issues. I can share it to you offline.

**Comment by Gpwner** [comment]
@namisan Can you share you converting tool to a single GitHub repository,Thanks.

**Comment by Gpwner** [comment]
@namisan By the way,I think the instruction of training a large MT-DNN is MTL task.I want to train a pretrain model on my custom data.

**Comment by namisan** [comment]
It doesn't support pretrain model with MLM now, and we'll consider it.

**Comment by Gpwner** [comment]
@namisan So how do you get your  bert_model_base.pt or  bert_model_large.pt? Does the converting you mentioned is the convention of bert pretrain model from tensorflow format to  pytorch format?

If so ,can you share your converting tool on GitHub?
Appreciate in advance!
