### ISSUE TITLE
No such file or directory: 'data/mt_dnn/mnli_train.json'

### ISSUE THREAD

**Issue by 156aasdfg** [namisan/mt-dnn#57]
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
Namespace(answer_att_hidden_size=128, answer_att_type='bilinear', answer_dropout_p=0.1, answer_mem_drop_p=0.1, answer_mem_type=1, answer_merge_opt=1, answer_num_turn=5, answer_opt=0, answer_rnn_type='gru', answer_sum_att_type='bilinear', answer_weight_norm_on=False, batch_size=8, batch_size_eval=8, bert_dropout_p=0.1, bert_l2norm=0.0, cuda=True, data_dir='data/mt_dnn', data_sort_on=False, dropout_p=0.1, dropout_w=0.0, dump_state_on=False, ema_gamma=0.995, ema_opt=0, embedding_opt=0, epochs=5, freeze_layers=-1, global_grad_clipping=1.0, grad_clipping=0, have_lr_scheduler=True, init_checkpoint='mt_dnn_models/bert_model_base.pt', init_ratio=1, label_size='3', learning_rate=5e-05, log_file='mt-dnn-train.log', log_per_updates=500, lr_gamma=0.5, max_seq_len=512, mem_cum_type='simple', mix_opt=0, momentum=0, mtl_opt=0, multi_gpu_on=False, multi_step_lr='10,20,30', name='farmer', optimizer='adamax', output_dir='checkpoint', pw_tasks=['qnnli'], ratio=0, scheduler_type='ms', seed=2018, task_config_path='configs/tasks_config.json', test_datasets=['mnli_mismatched', 'mnli_matched'], train_datasets=['mnli'], update_bert_opt=0, vb_dropout=True, warmup=0.1, warmup_schedule='warmup_linear', weight_decay=0)
07/01/2019 01:37:37 0
07/01/2019 01:37:37 Launching the MT-DNN training
07/01/2019 01:37:37 Loading data/mt_dnn/mnli_train.json as task 0
Traceback (most recent call last):
  File "train.py", line 350, in <module>
    main()
  File "train.py", line 178, in main
    train_data = BatchGen(BatchGen.load(train_path, True, pairwise=pw_task, maxlen=args.max_seq_len),
  File "/home/ubuntu/paraphrase/mt-dnn/mt_dnn/batcher.py", line 55, in load
    with open(path, 'r', encoding='utf-8') as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'data/mt_dnn/mnli_train.json'

I use the tutorial to train, what does this error mean? What does the Json file contain?

**Comment by 156aasdfg** [comment]
it is in another folder.
