### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by mazicwong** [namisan/mt-dnn#82]
In training model, when I use `python train.py --init_checkpoint='mt_dnn_models/bert_model_base_chinese.pt'`, 
Some error occur: `RuntimeError: CUDA error: device-side assert triggered`

However, when I replace this hyper-parameter with, for example, `bert_model_base_uncased.pt; bert_model_base_uncased.pt`, it can train normally.

But, it is obviously not what I want, I train it for a simple four-class classification task in chinese dataset, and want to use `bert_model_base_chinese.py` you provided.

Note that:
-  all model mentioned above are download by `download.sh`
- I have check out this [issue](https://github.com/pytorch/pytorch/issues/1204) previously in pytorch repo, also it could not give me any helps.

**Comment by mazicwong** [comment]
Paste the complete error
```
08/15/2019 10:10:38 Task [ 0] updates[     1] train loss[1.20420] remaining[0:25:15]
Traceback (most recent call last):
  File "train.py", line 396, in <module>
    main()
  File "train.py", line 351, in main
    model.update(batch_meta, batch_data) 
  File "/data1/zqhuang/mtdnn/mt-dnn-master/mt_dnn/model.py", line 150, in update
    logits = self.mnetwork(*inputs)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/zqhuang/mtdnn/mt-dnn-master/mt_dnn/matcher.py", line 99, in forward
    all_encoder_layers, pooled_output = self.bert(input_ids, token_type_ids, attention_mask)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 881, in forward
    head_mask=head_mask)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 498, in forward
    hidden_states = layer_module(hidden_states, attention_mask, head_mask[i])
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 480, in forward
    layer_output = self.output(intermediate_output, attention_output)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 462, in forward
    hidden_states = self.LayerNorm(hidden_states + input_tensor)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/zqhuang/anaconda3/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 289, in forward
    x = (x - u) / torch.sqrt(s + self.variance_epsilon)
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by mazicwong** [comment]
Paste the data I used to train
```
$ head -n 3 data/canonical_data/mt_dnn_b_cased_lower/yesno_dev.json 

{"uid": "0", "label": 0, "token_id": [101, 1372, 6206, 860, 1798, 2345, 6655, 1166, 1920, 4638, 1922, 6814, 1146, 511, 1469, 818, 862, 1501, 4905, 6963, 1377, 809, 6981, 4905, 511, 102], "type_id": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
{"uid": "1", "label": 0, "token_id": [101, 1880, 5988, 3221, 4660, 6001, 117, 2124, 1391, 6011, 2094, 4638, 102], "type_id": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
{"uid": "2", "label": 3, "token_id": [101, 1880, 5988, 679, 3221, 6001, 8024, 3221, 4260, 6121, 1220, 4289, 800, 812, 1391, 6011, 2094, 5721, 6066, 784, 720, 4638, 8024, 3221, 3300, 4660, 4638, 102], "type_id": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
```

And supply more infomations:
```
Size of vocab.txt: 30522
Has set --label_size=4 in train.py
```
Thanks and waiting for your help :)

**Comment by Shi-ma** [comment]
It's maybe same as following problem https://github.com/huggingface/transformers/issues/1805. The vocab size of BERT-Base-Chinese is 21128. Please check vocab size of pre-trained model and training config.

**Comment by namisan** [comment]
@Shi-ma yes, when index is out of array, it gives similar errors. 
@mazicwong  make sure you used a correct tokenizer/vocab.
