### ISSUE TITLE
Issue in preprocessing data

### ISSUE THREAD

**Issue by zeeshansayyed** [namisan/mt-dnn#87]
I downloaded the data using the download script and ran the prepro.sh script as given in the readme and it runs into the following error:

```
sh experiments/glue/prepro.sh
08/28/2019 11:18:45 Loaded 23596 SciTail train samples
08/28/2019 11:18:45 Loaded 1304 SciTail dev samples
08/28/2019 11:18:45 Loaded 2126 SciTail test samples
08/28/2019 11:18:47 Loaded 549367 SNLI train samples
08/28/2019 11:18:47 Loaded 9842 SNLI dev samples
08/28/2019 11:18:47 Loaded 9824 SNLI test samples
08/28/2019 11:18:48 Loaded 392702 MNLI train samples
08/28/2019 11:18:48 Loaded 9815 MNLI matched dev samples
08/28/2019 11:18:48 Loaded 9832 MNLI mismatched dev samples
08/28/2019 11:18:48 Loaded 9796 MNLI matched test samples
08/28/2019 11:18:48 Loaded 9847 MNLI mismatched test samples
08/28/2019 11:18:48 Loaded 3668 MRPC train samples
08/28/2019 11:18:48 Loaded 408 MRPC dev samples
08/28/2019 11:18:48 Loaded 1725 MRPC test samples
08/28/2019 11:18:49 Loaded 104743 QNLI train samples
08/28/2019 11:18:49 Loaded 5463 QNLI dev samples
08/28/2019 11:18:49 Loaded 5463 QNLI test samples
08/28/2019 11:18:50 Loaded 363846 QQP train samples
08/28/2019 11:18:50 Loaded 40430 QQP dev samples
08/28/2019 11:18:50 Loaded 390965 QQP test samples
08/28/2019 11:18:50 Loaded 2490 RTE train samples
08/28/2019 11:18:50 Loaded 277 RTE dev samples
08/28/2019 11:18:50 Loaded 3000 RTE test samples
08/28/2019 11:18:50 Loaded 635 WNLI train samples
08/28/2019 11:18:50 Loaded 71 WNLI dev samples
08/28/2019 11:18:50 Loaded 146 WNLI test samples
08/28/2019 11:18:50 Loaded 67349 SST train samples
08/28/2019 11:18:50 Loaded 872 SST dev samples
08/28/2019 11:18:50 Loaded 1821 SST test samples
08/28/2019 11:18:50 Loaded 8551 COLA train samples
08/28/2019 11:18:50 Loaded 1043 COLA dev samples
08/28/2019 11:18:50 Loaded 1063 COLA test samples
08/28/2019 11:18:50 Loaded 5749 STS-B train samples
08/28/2019 11:18:50 Loaded 1500 STS-B dev samples
08/28/2019 11:18:50 Loaded 1379 STS-B test samples
08/28/2019 11:18:50 done with scitail
08/28/2019 11:18:52 done with snli
08/28/2019 11:18:54 done with mnli
08/28/2019 11:18:54 done with mrpc
08/28/2019 11:18:54 done with qnli
08/28/2019 11:18:57 done with qqp
08/28/2019 11:18:57 done with rte
08/28/2019 11:18:57 done with wnli
08/28/2019 11:18:57 done with sst
08/28/2019 11:18:58 done with cola
08/28/2019 11:18:58 done with stsb
Traceback (most recent call last):
  File "prepro_std.py", line 7, in <module>
    from pytorch_pretrained_bert.tokenization import BertTokenizer
  File "/home/ec2-user/anaconda3/envs/ms_mtdnn/lib/python3.6/site-packages/pytorch_pretrained_bert/__init__.py", line 7, in <module>
    from .modeling import (BertConfig, BertModel, BertForPreTraining,
  File "/home/ec2-user/anaconda3/envs/ms_mtdnn/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 218, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm as BertLayerNorm
  File "/home/ec2-user/anaconda3/envs/ms_mtdnn/lib/python3.6/site-packages/apex/__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "/home/ec2-user/anaconda3/envs/ms_mtdnn/lib/python3.6/site-packages/apex/interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "/home/ec2-user/anaconda3/envs/ms_mtdnn/lib/python3.6/site-packages/apex/interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "/home/ec2-user/anaconda3/envs/ms_mtdnn/lib/python3.6/site-packages/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
```

**Comment by zeeshansayyed** [comment]
I have installed the same from the requirements file present in the repository, so it is 0.6.0. Is there a  problem with this one?

**Comment by zeeshansayyed** [comment]
Weirdly it was due to apex installation. I untilled the one from pip and built it from source to fix this problem.

**Comment by bashartalafha** [comment]
As mentioned in https://github.com/NVIDIA/apex

> we recommend installing Apex with CUDA and C++ extensions via


```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir ./

```
